version: '3'
services:
  redis-local:
    container_name: redis-local
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis-local-data:/data
volumes:
  redis-local-data:
